namespace Locan.Generator.Sources;

internal static class LocalizationModuleAttributeSource
{
	public const string Name =
		"Locan.Generator.Attributes.LocalizationModuleAttribute";

	public const string HintName = "LocalizationModuleAttribute.g.cs";

	public const string Source = """
		// <auto-generated/>
		#nullable enable

		namespace Locan.Generator.Attributes
		{
			[global::System.AttributeUsage(
				global::System.AttributeTargets.Assembly,
				AllowMultiple = false)]
			public sealed class LocalizationModuleAttribute : global::System.Attribute
			{
				public LocalizationModuleAttribute(string name)
				{
					Name = name;
				}

				public string Name { get; }

				public bool IsInternal { get; set; }
			}
		}
		""";
}
