using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Locan.Generator.Extensions;
using Locan.Generator.Models;

namespace Locan.Generator.Generation;

internal static class MessageClassSourceBuilder
{
	private const string BaseClass = "global::Locan.Core.LocalizableMessages.LocalizableMessage";

	public static string Build(ModuleOptions module, MessageDefinition definition)
	{
		using var stringWriter = new StringWriter(CultureInfo.InvariantCulture);
		using var writer = new IndentedTextWriter(stringWriter, "\t");
		var placeholders = definition.Placeholders.Values.ToList();
		var methodNames = CreateMethodNames(definition);

		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine("#nullable enable");
		writer.WriteLine();
		writer.WriteLine($"namespace {module.Name}");
		writer.OpenBlock();
		WriteClassDocumentation(writer, definition, placeholders);
		writer.WriteLine(
			$"{GetAccessibility(module)} partial class {definition.ClassName} : {BaseClass}");
		writer.OpenBlock();
		writer.WriteLine($"public const string Key = {CSharpNames.Literal(definition.Key)};");
		writer.WriteLine();

		WriteConstructor(writer, definition);
		writer.WriteLine();
		WriteFactoryMethod(writer, definition, placeholders);

		foreach (var placeholder in placeholders)
		{
			writer.WriteLine();
			WritePlaceholderMethod(
				writer,
				definition,
				placeholder,
				methodNames[placeholder.Key]);
		}

		writer.CloseBlock();
		writer.CloseBlock();

		return stringWriter.ToString();
	}

	private static string GetAccessibility(ModuleOptions module) =>
		module.IsInternal ? "internal" : "public";

	private static void WriteClassDocumentation(
		IndentedTextWriter writer,
		MessageDefinition definition,
		List<PlaceholderInfo> placeholders)
	{
		writer.WriteLine("/// <summary>");
		writer.WriteLine($"/// Localization message <c>{Xml(definition.Key)}</c>.");
		writer.WriteLine($"/// <para>Default culture template: <c>{Xml(definition.Template)}</c></para>");
		writer.WriteLine("/// </summary>");

		if (placeholders.Count == 0)
			return;

		writer.WriteLine("/// <remarks>");
		writer.WriteLine("/// <para>Placeholders:<br/>");

		foreach (var placeholder in placeholders)
			writer.WriteLine(
				$"/// <c>{Xml(placeholder.Key)}</c> — " +
				$"{GetPlaceholderDescription(placeholder)}<br/>");

		writer.WriteLine("/// </para>");
		writer.WriteLine("/// </remarks>");
	}

	private static void WriteConstructor(
		IndentedTextWriter writer,
		MessageDefinition definition)
	{
		writer.WriteLine($"public {definition.ClassName}() : base(Key)");
		writer.OpenBlock();
		writer.CloseBlock();
	}

	private static void WriteFactoryMethod(
		IndentedTextWriter writer,
		MessageDefinition definition,
		List<PlaceholderInfo> placeholders)
	{
		var parameters = new List<string>();

		foreach (var placeholder in placeholders)
			parameters.Add(
				$"{CSharpNames.GetTypeName(placeholder.Type)} " +
				CSharpNames.EscapeIdentifier(placeholder.Key));

		writer.WriteLine($"/// <summary>Creates a <see cref=\"{definition.ClassName}\"/>.</summary>");

		foreach (var placeholder in placeholders)
			writer.WriteLine(
				$"/// <param name=\"{Xml(placeholder.Key)}\">" +
				$"{GetPlaceholderDescription(placeholder)}</param>");

		writer.WriteLine("/// <returns>The initialized localization message.</returns>");

		writer.WriteLine(
			$"public static {definition.ClassName} Create({string.Join(", ", parameters)})");
		writer.OpenBlock();
		writer.WriteLine($"var message = new {definition.ClassName}();");

		foreach (var placeholder in placeholders)
			writer.WriteLine(GetWithValueInvocation(
				"message.",
				placeholder,
				CSharpNames.EscapeIdentifier(placeholder.Key)));

		writer.WriteLine("return message;");
		writer.CloseBlock();
	}

	private static void WritePlaceholderMethod(
		IndentedTextWriter writer,
		MessageDefinition definition,
		PlaceholderInfo placeholder,
		string methodName)
	{
		writer.WriteLine(
			$"public {definition.ClassName} {methodName}(" +
			$"{CSharpNames.GetTypeName(placeholder.Type)} value)");
		writer.OpenBlock();
		writer.WriteLine(GetWithValueInvocation(string.Empty, placeholder, "value"));
		writer.WriteLine("return this;");
		writer.CloseBlock();
	}

	private static string GetWithValueInvocation(
		string target,
		PlaceholderInfo placeholder,
		string value)
	{
		var format = string.IsNullOrWhiteSpace(placeholder.Format)
			? string.Empty
			: $", {CSharpNames.Literal(placeholder.Format)}";

		return $"{target}WithValue({CSharpNames.Literal(placeholder.Key)}, {value}{format});";
	}

	private static IReadOnlyDictionary<string, string> CreateMethodNames(
		MessageDefinition definition)
	{
		var result = new Dictionary<string, string>(StringComparer.Ordinal);
		var usedNames = new HashSet<string>(StringComparer.Ordinal);

		foreach (var placeholder in definition.Placeholders.Values)
		{
			var baseName = "With" + CSharpNames.NormalizeClassName(placeholder.Key);
			var methodName = baseName;
			var suffix = 1;

			while (string.Equals(methodName, definition.ClassName, StringComparison.Ordinal) ||
			       !usedNames.Add(methodName))
			{
				methodName = suffix == 1
					? baseName + "Placeholder"
					: baseName + "Placeholder" + suffix;
				suffix++;
			}

			result.Add(placeholder.Key, methodName);
		}

		return result;
	}

	private static string GetPlaceholderDescription(PlaceholderInfo placeholder)
	{
		var description =
			$"Type: <c>{Xml(CSharpNames.GetTypeName(placeholder.Type))}</c>.";

		if (!string.IsNullOrWhiteSpace(placeholder.Format))
			description += $" Format: <c>{Xml(placeholder.Format!)}</c>.";

		return description;
	}

	private static string Xml(string value) =>
		value.Replace("&", "&amp;")
			.Replace("<", "&lt;")
			.Replace(">", "&gt;")
			.Replace("\"", "&quot;")
			.Replace("'", "&apos;");
}
