using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Locan.Generator.Extensions;
using Locan.Generator.Models;

namespace Locan.Generator.Generation;

internal static class MessageClassSourceBuilder
{
	private const string BaseClass = "global::Locan.LocalizableMessages.LocalizableMessage";

	public static string Build(ModuleOptions module, MessageDefinition definition)
	{
		using var stringWriter = new StringWriter(CultureInfo.InvariantCulture);
		using var writer = new IndentedTextWriter(stringWriter, "\t");
		var placeholders = definition.Placeholders.Values.ToList();
		var methodNames = CreateMethodNames(definition);

		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine("#nullable enable");
		writer.WriteLine();
		writer.WriteLine($"namespace {module.Name}");
		writer.OpenBlock();
		writer.WriteLine(
			$"{GetAccessibility(module)} partial class {definition.ClassName} : {BaseClass}");
		writer.OpenBlock();
		writer.WriteLine($"public const string Key = {CSharpNames.Literal(definition.Key)};");
		writer.WriteLine();

		WriteConstructor(writer, definition);
		writer.WriteLine();
		WriteFactoryMethod(writer, definition, placeholders);

		foreach (var placeholder in placeholders)
		{
			writer.WriteLine();
			WritePlaceholderMethod(
				writer,
				definition,
				placeholder,
				methodNames[placeholder.Key]);
		}

		writer.WriteLine();
		WriteFormatMethod(writer);
		writer.CloseBlock();
		writer.CloseBlock();

		return stringWriter.ToString();
	}

	private static string GetAccessibility(ModuleOptions module) =>
		module.IsInternal ? "internal" : "public";

	private static void WriteConstructor(
		IndentedTextWriter writer,
		MessageDefinition definition)
	{
		writer.WriteLine($"public {definition.ClassName}() : base(Key)");
		writer.OpenBlock();
		writer.CloseBlock();
	}

	private static void WriteFactoryMethod(
		IndentedTextWriter writer,
		MessageDefinition definition,
		List<PlaceholderInfo> placeholders)
	{
		var parameters = new List<string>();

		foreach (var placeholder in placeholders)
			parameters.Add(
				$"{CSharpNames.GetTypeName(placeholder.Type)} " +
				CSharpNames.EscapeIdentifier(placeholder.Key));

		writer.WriteLine(
			$"public static {definition.ClassName} Create({string.Join(", ", parameters)})");
		writer.OpenBlock();
		writer.WriteLine($"var message = new {definition.ClassName}();");

		foreach (var placeholder in placeholders)
			writer.WriteLine(
				$"message.WithValue({CSharpNames.Literal(placeholder.Key)}, " +
				$"FormatValue({CSharpNames.EscapeIdentifier(placeholder.Key)}, " +
				$"{CSharpNames.Literal(placeholder.Format)}));");

		writer.WriteLine("return message;");
		writer.CloseBlock();
	}

	private static void WritePlaceholderMethod(
		IndentedTextWriter writer,
		MessageDefinition definition,
		PlaceholderInfo placeholder,
		string methodName)
	{
		writer.WriteLine(
			$"public {definition.ClassName} {methodName}(" +
			$"{CSharpNames.GetTypeName(placeholder.Type)} value)");
		writer.OpenBlock();
		writer.WriteLine(
			$"WithValue({CSharpNames.Literal(placeholder.Key)}, " +
			$"FormatValue(value, {CSharpNames.Literal(placeholder.Format)}));");
		writer.WriteLine("return this;");
		writer.CloseBlock();
	}

	private static void WriteFormatMethod(IndentedTextWriter writer)
	{
		writer.WriteLine("private static string? FormatValue<T>(T value, string? format)");
		writer.OpenBlock();
		writer.WriteLine("if (value is null)");
		writer.OpenBlock();
		writer.WriteLine("return null;");
		writer.CloseBlock();
		writer.WriteLine();
		writer.WriteLine("if (value is global::System.IFormattable formattable)");
		writer.OpenBlock();
		writer.WriteLine(
			"return formattable.ToString(format, " +
			"global::System.Globalization.CultureInfo.InvariantCulture);");
		writer.CloseBlock();
		writer.WriteLine();
		writer.WriteLine("return value.ToString();");
		writer.CloseBlock();
	}

	private static IReadOnlyDictionary<string, string> CreateMethodNames(
		MessageDefinition definition)
	{
		var result = new Dictionary<string, string>(StringComparer.Ordinal);
		var usedNames = new HashSet<string>(StringComparer.Ordinal);

		foreach (var placeholder in definition.Placeholders.Values)
		{
			var baseName = "With" + CSharpNames.NormalizeClassName(placeholder.Key);
			var methodName = baseName;
			var suffix = 1;

			while (string.Equals(methodName, definition.ClassName, StringComparison.Ordinal) ||
			       !usedNames.Add(methodName))
			{
				methodName = suffix == 1
					? baseName + "Placeholder"
					: baseName + "Placeholder" + suffix;
				suffix++;
			}

			result.Add(placeholder.Key, methodName);
		}

		return result;
	}
}
