//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace Locan.Compiler;

internal static class Resources
{
	private static ResourceManager? _resourceManager;

	internal static ResourceManager ResourceManager =>
		_resourceManager ??= new ResourceManager("Locan.Compiler.Resources", typeof(Resources).Assembly);

	internal static CultureInfo? Culture { get; set; }

	internal static string LOCAN001Title => GetString(nameof(LOCAN001Title));
	internal static string LOCAN001MessageFormat => GetString(nameof(LOCAN001MessageFormat));
	internal static string LOCAN002Title => GetString(nameof(LOCAN002Title));
	internal static string LOCAN002MessageFormat => GetString(nameof(LOCAN002MessageFormat));
	internal static string LOCAN003Title => GetString(nameof(LOCAN003Title));
	internal static string LOCAN003MessageFormat => GetString(nameof(LOCAN003MessageFormat));
	internal static string LOCAN004Title => GetString(nameof(LOCAN004Title));
	internal static string LOCAN004MessageFormat => GetString(nameof(LOCAN004MessageFormat));
	internal static string LOCAN005Title => GetString(nameof(LOCAN005Title));
	internal static string LOCAN005MessageFormat => GetString(nameof(LOCAN005MessageFormat));
	internal static string AB0001Description => GetString(nameof(AB0001Description));
	internal static string AB0001MessageFormat => GetString(nameof(AB0001MessageFormat));
	internal static string AB0001Title => GetString(nameof(AB0001Title));
	internal static string AB0001CodeFixTitle => GetString(nameof(AB0001CodeFixTitle));
	internal static string AB0002Description => GetString(nameof(AB0002Description));
	internal static string AB0002MessageFormat => GetString(nameof(AB0002MessageFormat));
	internal static string AB0002Title => GetString(nameof(AB0002Title));

	private static string GetString(string name) => ResourceManager.GetString(name, Culture)!;
}
